name: C/C++ CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: compile test binary
              run: make release -j4
            - name: test
              run: cd test && ../sedimentation testfile.asm -o test
            - name: check output of test file
              run: cd test && ./test | diff - output.txt
