name: C/C++ CI

on:
    push:
        branches: ["main", "dev"]
    pull_request:
        branches: ["main"]

jobs:
    linux-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: compile test binary
              run: make release -j4
            - name: Test normal assembling
              run: |
                  cd test
                  ../sedimentation testfile.asm -o test.o
                  ld test.o -o test
                  ./test | diff - testfile.out
            - name: Test assembling with external symbols
              run: |
                  cd test
                  ../sedimentation testc.asm -o testc.o
                  gcc -nostartfiles testc.o -o testc
                  ./testc | diff - testc.out
            - name: Test SSE instructions
              run: |
                  cd test
                  ../sedimentation testsse.asm -o testsse.o
                  gcc -nostartfiles testsse.o -o testsse
                  ./testsse | diff - testsse.out
            - name: Test AVX instructions
              run: |
                  cd test
                  ../sedimentation testavx.asm -o testavx.o
                  gcc -nostartfiles testavx.o -o testavx
                  ./testavx | diff - testavx.out

    windows-test:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v3
            - name: compile test binary
              run: make release -j4
            - name: Test normal assembling
              run: |
                  cd test
                  ../sedimentation testfile.asm -o test.obj -f coff
                  ld test.obj -o test
                  test.exe > test.out.1
                  diff (cat testfile.out.1) (cat testfile.out)
            - name: Test assembling with external symbols
              run: |
                  cd test
                  ../sedimentation testc.asm -o testc.obj -f coff
                  gcc -nostartfiles testc.obj -o testc
                  testc.exe > testc.out.1
                  diff (cat testc.out.1) (cat testc.out)
            - name: Test SSE instructions
              run: |
                  cd test
                  ../sedimentation testsse.asm -o testsse.obj -f coff
                  gcc -nostartfiles testsse.obj -o testsse
                  testsse.exe > testsse.out.1
                  diff (cat testsse.out.1) (cat testsse.out)
            - name: Test AVX instructions
              run: |
                  cd test
                  ../sedimentation testavx.asm -o testavx.obj -f coff
                  gcc -nostartfiles testavx.obj -o testavx
                  testavx.exe > testavx.out.1
                  diff (cat testavx.out.1) (cat testavx.out)
